[libraries]

# Gradle Plugins
gradle-android = "com.android.tools.build:gradle:8.9.2"
gradle-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.21"
gradle-testlogger = "com.adarshr:gradle-test-logger-plugin:4.0.0"
gradle-kotlinx-serialization = "org.jetbrains.kotlin:kotlin-serialization:2.1.21"
gradle-dropshots = "com.dropbox.dropshots:dropshots-gradle-plugin:0.4.1"
gradle-emulator-wtf = "wtf.emulator:gradle-plugin:0.18.1"

# Kotlinx
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-coroutines-jvm = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
kotlinx-coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2"
kotlinx-serialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.8.1"
kotlinx-serialization-jvm = "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.8.1"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1"

# Androidx
androidx-core = "androidx.core:core:1.16.0"
androidx-core-ktx = "androidx.core:core-ktx:1.16.0"
androidx-activity-ktx = "androidx.activity:activity-ktx:1.10.1"
androidx-lifecycle-common = "androidx.lifecycle:lifecycle-common:2.9.2"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.9.2"
androidx-lifecycle-vm = "androidx.lifecycle:lifecycle-viewmodel:2.9.2"
androidx-lifecycle-vm-ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2"
androidx-appcompat = "androidx.appcompat:appcompat:1.7.1"
androidx-swipetorefresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
androidx-coordinatorlayout = "androidx.coordinatorlayout:coordinatorlayout:1.3.0"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-test-core = "androidx.test:core:1.7.0"
androidx-test-corektx = "androidx.test:core-ktx:1.7.0"
androidx-testext-junit = "androidx.test.ext:junit:1.3.0"
androidx-testext-junitktx = "androidx.test.ext:junit-ktx:1.2.1"
androidx-test-runner = "androidx.test:runner:1.7.0"
androidx-test-rules = "androidx.test:rules:1.7.0"
androidx-test-monitor = "androidx.test:monitor:1.8.0"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
androidx-espresso-intents = "androidx.test.espresso:espresso-intents:3.7.0"

# Google
google-truth = "com.google.truth:truth:1.4.4"
google-material-design = "com.google.android.material:material:1.12.0"

# Square / CashApp
square-okhttp-core = "com.squareup.okhttp3:okhttp:4.12.0"
square-okhttp-logging = "com.squareup.okhttp3:logging-interceptor:4.12.0"
square-retrofit = "com.squareup.retrofit2:retrofit:2.11.0"
square-radiography = "com.squareup.radiography:radiography:2.7"
square-leakcanary-core = "com.squareup.leakcanary:leakcanary-android:2.14"
square-leakcanary-instrumentation = "com.squareup.leakcanary:leakcanary-android-instrumentation:2.14"
jw-retrofit-kotlinx = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"
cashapp-turbine = "app.cash.turbine:turbine:1.2.1"

# Resilience4j
resilience4j-retry = "io.github.resilience4j:resilience4j-retry:2.3.0"
resilience4j-kotlin = "io.github.resilience4j:resilience4j-kotlin:2.3.0"

# Other / Testing
junit4 = "junit:junit:4.13.2"
slf4j = "org.slf4j:slf4j-nop:2.0.17"
robolectric = "org.robolectric:robolectric:4.14.1"
adevinta-barista = "com.adevinta.android:barista:4.3.0"
dropshots = "com.dropbox.dropshots:dropshots:0.4.1"
testcontainers-core = "org.testcontainers:testcontainers:1.20.6"
testcontainers-toxyproxy = "org.testcontainers:toxiproxy:1.20.6"

# Security patches
forced-jsoup = "org.jsoup:jsoup:1.19.1"
forced-okio = "com.squareup.okio:okio:3.10.2"
